images:
  - nginx:latest
  - alpine:latest
  - registry:latest
  - minio/minio:latest
  - archlinux:latest
  - joxit/docker-registry-ui:main
  - rzrbld/adminio-ui:latest
  - docker.getoutline.com/outlinewiki/outline:latest
  - postgres:18
  - matrixdotorg/synapse:latest
  - matrixdotorg/sygnal:latest
  - matrixdotorg/dendrite-monolith:latest
  - linuxserver/qbittorrent:5.1.2
  - ghcr.io/fatedier/frps:v0.65.0
  - grafana/grafana
  - grafana/loki
  - prom/prometheus:main
  - jitsi/base:stable
  - jitsi/base-java:stable
  - jitsi/prosody:stable
  - jitsi/jicofo:stable
  - jitsi/jvb:stable
  - jitsi/web:stable
  - jitsi/jigasi:stable
  - jitsi/jibri:stable
  - jitsi/jitsi-multitrack-recorder
  - mlikiowa/napcat-docker:latest
  - binwiederhier/ntfy
  - line/promgen
  - rustdesk/rustdesk-server
  - ghcr.io/sillytavern/sillytavern
  - docker.gitea.com/gitea:latest
  - keycloak/keycloak
  - netbirdio/netbird:latest
  - nixos/nix
  - sigoden/dufs
  - openlistteam/openlist:latest
  - triliumnext/trilium:main
  - ghcr.io/bitwarden/self-host:latest
  - linuxserver/jellyfin
  - ghcr.io/element-hq/element-call:latest-ci
  - louislam/uptime-kuma
  - powerdns/pdns-auth-50
  - ghcr.io/poweradmin/poweradmin:latest
  - acspri/limesurvey
  - coturn/coturn
  - ghcr.io/dani-garcia/vaultwarden:latest
  - docker.io/chrislusf/seaweedfs:latest
  - quay.io/prometheus/blackbox-exporter:latest
  - ghcr.io/etkecc/synapse-admin
  - discourse/base:release
  - ghcr.io/thomiceli/opengist:latest
