---
- name: Preprocess image name
  ansible.builtin.set_fact:
    clean_image_name: >-
      {{
        image_name
        | regex_replace('^docker\\.io/', '')
        | regex_replace('^ghcr\\.io/', '')
      }}

- name: Tag image for target registry
  ansible.builtin.shell: |
    echo "Tagging image: {{ image_name }} -> {{ registry_host }}/{{ clean_image_name }}"
    docker tag {{ image_name }} {{ registry_host }}/{{ clean_image_name }}
  register: tag_result
  retries: 3
  delay: 5
  until: tag_result.rc == 0
  changed_when: true

- name: Push image to target registry
  ansible.builtin.shell: |
    echo "Pushing image: {{ registry_host }}/{{ clean_image_name }}"
    docker push {{ registry_host }}/{{ clean_image_name }}
  register: push_result
  retries: 5
  delay: 10
  until: push_result.rc == 0
  changed_when: true

- name: Show push summary
  ansible.builtin.debug:
    msg: |
      Successfully pushed: {{ registry_host }}/{{ clean_image_name }}
