---
- name: pre-processing image names
  ansible.builtin.set_fact:
    image_name: "{{ image_name | regex_replace('^docker.io/', '') | regex_replace('^ghcr.io/', '') }}"

- name: Tag image for target registry
  ansible.builtin.shell: |
    docker tag \
    $(docker images --format '{{"{{.Repository}}:{{.Tag}}"}}' | grep {{ image_name }}) \
    {{ registry_host }}/{{ image_name }}
  register: tag_result
  retries: 3
  delay: 5
  until: tag_result.rc == 0

- name: Push image to target registry
  ansible.builtin.shell: |
    if [ "{{ registry_is_https }}" = "True" ]; then
      docker push {{ registry_host }}/{{ image_name }}
    else
      echo "⚠️  Using HTTP for push: http://{{ registry_host }}/{{ image_name }}"
      docker push http://{{ registry_host }}/{{ image_name }}
    fi
  register: push_result
  retries: 5
  delay: 10
  until: push_result.rc == 0
# - name: Debug Push result
#   ansible.builtin.debug:
#     msg: "Successfully pushed {{ registry_host }}/{{ image_name }}"
#   when: push_result is succeeded
