---
- name: Create apt keys directory
  file:
    path: /usr/local/apt-keys
    state: directory
    mode: "0755"

- name: Download GPG key
  ansible.builtin.get_url:
    url: https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt
    dest: /tmp/key.asc

- name: Convert GPG key to binary format
  command: gpg --dearmor -o /usr/local/apt-keys/yggdrasil-keyring.gpg /tmp/key.asc
  args:
    creates: /usr/local/apt-keys/yggdrasil-keyring.gpg

- name: Remove temporary key
  file:
    path: /tmp/key.asc
    state: absent

- name: Add Yggdrasil repository
  copy:
    dest: /etc/apt/sources.list.d/yggdrasil.list
    content: "deb [signed-by=/usr/local/apt-keys/yggdrasil-keyring.gpg] http://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/ debian yggdrasil"

- name: Install Yggdrasil package
  apt:
    name: yggdrasil
    state: present
    update_cache: yes

- name: Start Yggdrasil service
  ansible.builtin.systemd:
    name: yggdrasil
    enabled: yes
    state: started
    daemon_reload: yes

- name: Ensure Yggdrasil service is running
  block:
    - name: Check connectivity
      command: yggdrasilctl getSelf
      register: self_check
      changed_when: false
      failed_when: self_check.rc != 0

  rescue:
    - name: Restart service if checks failed
      systemd:
        name: yggdrasil
        state: restarted

    - debug:
        msg: "Yggdrasil service restarted due to startup issues"

- name: Add Yggdrasil peer
  command: "yggdrasilctl addpeer {{ vault_endpoint }}"
  changed_when: false

- name: Add Yggdrasil hosts entry
  lineinfile:
    path: /etc/hosts
    line: "{{ vault_hosts }}"
    state: present
