---
- name: Sync container images from ghcr or Docker Hub
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../config/images.yml
    - ../ansible/vault.yml

  vars:
    target_registry: "{{ target_registry | default(vault_registry_url, true) }}"

  tasks:
    - name: Ensure registry vars are loaded
      ansible.builtin.debug:
        msg:
          - "Target registry: {{ target_registry }}"
          - "Auth mode: Basic"
          - "Vault user: {{ vault_registry_username | default('undefined') }}"

    - name: Login to target registry using Basic Auth
      community.docker.docker_login:
        registry_url: "{{ target_registry }}"
        username: "{{ vault_registry_username }}"
        password: "{{ vault_registry_password }}"
        reauthorize: yes

    - name: Pull each image from ghcr.io or docker.io
      ansible.builtin.shell: |
        docker pull ghcr.io/{{ item }} || docker pull docker.io/{{ item }}
      loop: "{{ images }}"
      loop_control:
        label: "{{ item }}"
      register: pull_results
      failed_when: pull_results.rc != 0

    - name: Tag and push images to target registry
      include_tasks: tasks/push_image.yml
      loop: "{{ images }}"
      loop_control:
        loop_var: image_name
        label: "{{ image_name }}"

    - name: Verify each image exists in target registry
      ansible.builtin.shell: |
        docker manifest inspect {{ target_registry }}/{{ item }} > /dev/null
      register: verify_result
      failed_when: verify_result.rc != 0
      loop: "{{ images }}"
      loop_control:
        label: "{{ item }}"

    - name: Logout from target registry
      community.docker.docker_login:
        registry_url: "{{ target_registry }}"
        state: absent
